FROM alerta/alerta-web:5.2.3

LABEL Name="alerta"
LABEL Maintainer="thibaut.allain@orange.com"
LABEL Description="Alerta for monitoring"
LABEL Url="https://gitlab.forge.orange-labs.fr/dwtg7375/alerta"
LABEL Version="1.0"

# Set http and https proxy 
#ENV http_proxy=http://apt.rd.francetelecom.fr:3142
#ENV https_proxy=http://apt.rd.francetelecom.fr:3142

ENV ALERTA_SVR_CONF_FILE /app/alertad.conf
ENV ALERTA_CONF_FILE /app/alerta.conf
ENV ALERTA_WEB_CONF_FILE /web/config.js

ENV BASE_URL /api
ENV PROVIDER basic
ENV PLUGINS "reject,blackout,normalise,enhance,slack,prometheus"
ENV INSTALL_PLUGINS "slack,prometheus"

EXPOSE 8080

USER root

#COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY supervisord.conf /app/supervisord.conf

USER 1001

#ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/app/supervisord.conf"]

HEALTHCHECK --timeout=10s --retries=3 \
  CMD ps aux | grep [s]upervisord || exit 1
